services:
  database:
    container_name: sql
    image: postgres:16.1-alpine3.18
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  
  server:
    container_name: server-instances
    image: server
    build:
      context: .
      dockerfile: ./Dockerfile.server
    depends_on:
       database:
          condition: service_healthy
    restart: always
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_PASSWORD=root
    ports:
      - 80:80
      - "5432"
  

  

    
